---
version: "3.8"

services:
  rethinkdb:
    build: ./rethinkdb/
    volumes:
      - backstop-db:/data/rethinkdb_data
    ports:
      - "5050:8080"
      - "29015:29015"
      - "28015:28015"
    networks:
      - backstop
    restart: on-failure
  data_domain:
    build: ./data_domain/
    volumes:
      - ./data_domain:/app/data_domain
    ports:
      - "6040:6040"
    networks:
      - backstop
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
    restart: on-failure
  calculator:
    build: ./calculator/
    volumes:
      - ./calculator:/app/retriever
    ports:
      - "4060:4060"
    networks:
      - backstop
    environment:
      - DD_HOST=data_domain
      - DD_PORT=6040
    restart: on-failure
  edge:
    build: ./edge/
    volumes:
      - ./edge:/app
    networks:
      - backstop
    ports:
      - "8020:8020"
    environment:
      - DD_HOST=data_domain
      - DD_PORT=6040
      - CAL_HOST=calculator
      - CAL_PORT=4060
    restart: unless-stopped
    links:
      - data_domain
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - /app/node_modules
    depends_on: 
      - edge
    ports:
      - 1234
    networks:
      - backstop
    environment:
      - EDGE_HOST
      - EDGE_PORT
    restart: unless-stopped
    links:
      - edge
    command: "npm run start"
networks:
  backstop:
volumes:
  backstop-db:
